### ISSUE TITLE
android 7 camera problem build #54

### ISSUE THREAD

**Issue by dkryder** [ayufan-pine64/android-7.0#9]
hello. the csi camera has stopped working on this build of 7. can't figure it out. it does work with the android 5.1 #16 build. any ideas on what to do. i have no /dev/video0.

**Comment by ayufan** [comment]
I did test that it does work.

There's surely problem with recording:

```
10-16 05:13:35.088 19865 19865 E MediaRecorder: start failed: -19
10-16 05:13:35.090 19865 19865 E CAM_VideoModule: Could not start media recorder. 
10-16 05:13:35.090 19865 19865 E CAM_VideoModule: java.lang.RuntimeException: start failed.
10-16 05:13:35.090 19865 19865 E CAM_VideoModule:   at android.media.MediaRecorder.start(Native Method)
10-16 05:13:35.090 19865 19865 E CAM_VideoModule:   at com.android.camera.VideoModule$11.onStorageUpdateDone(VideoModule.java:1393)
10-16 05:13:35.090 19865 19865 E CAM_VideoModule:   at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2351)
10-16 05:13:35.090 19865 19865 E CAM_VideoModule:   at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2346)
```

**Comment by ayufan** [comment]
This is solved.
